# Generated by Django 4.2.7 on 2026-02-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectapplication',
            new_name='project_app_project_889b01_idx',
            old_name='project_app_project_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='projectapplication',
            new_name='project_app_applica_8b7b33_idx',
            old_name='project_app_applica_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='projectlead',
            new_name='project_lea_status_005395_idx',
            old_name='project_lea_status_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='projectlead',
            new_name='project_lea_source__98b0c3_idx',
            old_name='project_lea_source__123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='projectlead',
            new_name='project_lea_is_publ_d07d93_idx',
            old_name='project_lea_is_publ_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmatch',
            new_name='project_mat_user_id_00b47a_idx',
            old_name='project_mat_user_id_123abc_idx',
        ),
    ]
