# Generated by Django 4.2.7 on 2026-02-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_rename_project_app_project_123abc_idx_project_app_project_889b01_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.JSONField(blank=True, default=list, help_text="List of keywords to match jobs to this category (e.g., ['SEO', 'search engine optimization', 'keyword research'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Scraping Config', help_text='Name for this scraping configuration', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active for scraping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(help_text='Categories to scrape jobs for', related_name='scraping_configs', to='projects.jobcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scraping_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scraping Configuration',
                'verbose_name_plural': 'Scraping Configurations',
                'db_table': 'scraping_configs',
            },
        ),
        migrations.AddField(
            model_name='projectlead',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this job belongs to', related_name='projects', to='projects.jobcategory'),
        ),
    ]
