# Generated by Django 4.2.7 on 2026-03-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectview',
            new_name='project_vie_user_id_6f1478_idx',
            old_name='project_views_user_viewed_at_idx',
        ),
    ]
